### ISSUE TITLE
Sample project doesn't work

### ISSUE THREAD

**Issue by VetaLioSTV** [TheEightBot/Xamarin.SideMenu#1]
Hi there. 
Thanks for the port of this great library.
Unfortunately the **sample** project have some errors,also can you please provide an example how to use this library via Storyboard(Xamarin.iOS Designer)!? 
Thanks!
<img width="841" alt="2017-02-18 17 32 26" src="https://cloud.githubusercontent.com/assets/15155286/23094381/722555fc-f600-11e6-9567-72a78e0928e1.png">

**Comment by michaelstonis** [comment]
We had a reference in there for a display debugging library. I removed it, so you should all be set there.

At the moment, we do not support adding this view via the storyboard designer. If you would like that feature, feel free to open up a separate issue.
