### ISSUE TITLE
Using with Mvvmcross

### ISSUE THREAD

**Issue by irmaosmanovic** [TheEightBot/Xamarin.SideMenu#7]
I tried to use SideMenu inside my mvvmcross project, but view is not loaded and app is crashing on ViewDidLoad because of null reference. Is package compatible with mvvmcross?

**Comment by michaelstonis** [comment]
I don't use MvvmCross, so I am not sure. Can you post a stack trace or a sample app that shows the issue?

**Comment by irmaosmanovic** [comment]
I already fixed, it's working with mvvmcros. Thank you for replay.

sri, 23. sij 2019. u 22:25 Michael Stonis <notifications@github.com>
napisao je:
